In [10]:
import kagglehub
import polars as pl
from pathlib import Path

In [9]:
datapath = kagglehub.dataset_download("thec03u5/seinfeld-chronicles")
datapath

'/home/trevor/.cache/kagglehub/datasets/thec03u5/seinfeld-chronicles/versions/1'

In [71]:
scripts = pl.scan_csv(Path(datapath, "scripts.csv")).with_columns([
    pl.col("EpisodeNo").cast(pl.Int8),
    pl.col("Season").cast(pl.Int8)
]).collect()
scripts

shape: (54_616, 6)
┌───────┬────────────┬─────────────────────────────────┬───────────┬────────┬────────┐
│       ┆ Character  ┆ Dialogue                        ┆ EpisodeNo ┆ SEID   ┆ Season │
│ ---   ┆ ---        ┆ ---                             ┆ ---       ┆ ---    ┆ ---    │
│ i64   ┆ str        ┆ str                             ┆ i8        ┆ str    ┆ i8     │
╞═══════╪════════════╪═════════════════════════════════╪═══════════╪════════╪════════╡
│ 0     ┆ JERRY      ┆ Do you know what this is all a… ┆ 1         ┆ S01E01 ┆ 1      │
│ 1     ┆ JERRY      ┆ (pointing at Georges shirt) Se… ┆ 1         ┆ S01E01 ┆ 1      │
│ 2     ┆ GEORGE     ┆ Are you through?                ┆ 1         ┆ S01E01 ┆ 1      │
│ 3     ┆ JERRY      ┆ You do of course try on, when … ┆ 1         ┆ S01E01 ┆ 1      │
│ 4     ┆ GEORGE     ┆ Yes, it was purple, I liked it… ┆ 1         ┆ S01E01 ┆ 1      │
│ …     ┆ …          ┆ …                               ┆ …         ┆ …      ┆ …      │
│ 54611 ┆ JERRY      ┆ Grand theft auto - don't steal… ┆ 23        ┆ S09E23 ┆ 9      │
│ 54612 ┆ PRISONER 3 ┆ You suck - I'm gonna cut you.   ┆ 23        ┆ S09E23 ┆ 9      │
│ 54613 ┆ JERRY      ┆ Hey, I don't come down to wher… ┆ 23        ┆ S09E23 ┆ 9      │
│ 54614 ┆ GUARD      ┆ Alright, Seinfeld, that's it. … ┆ 23        ┆ S09E23 ┆ 9      │
│ 54615 ┆ JERRY      ┆ Alright, hey, you've been grea… ┆ 23        ┆ S09E23 ┆ 9      │
└───────┴────────────┴─────────────────────────────────┴───────────┴────────┴────────┘

In [70]:
episode_info = pl.scan_csv(Path(datapath, "episode_info.csv")).with_columns([
    pl.col("EpisodeNo").cast(pl.Int8),
]).collect()
episode_info.tail()

shape: (5, 8)
┌─────┬────────┬───────────┬─────────────────┬────────────────┬────────────────┬──────────┬────────┐
│     ┆ Season ┆ EpisodeNo ┆ Title           ┆ AirDate        ┆ Writers        ┆ Director ┆ SEID   │
│ --- ┆ ---    ┆ ---       ┆ ---             ┆ ---            ┆ ---            ┆ ---      ┆ ---    │
│ i64 ┆ f64    ┆ i8        ┆ str             ┆ str            ┆ str            ┆ str      ┆ str    │
╞═════╪════════╪═══════════╪═════════════════╪════════════════╪════════════════╪══════════╪════════╡
│ 169 ┆ 9.0    ┆ 17        ┆ The Bookstore   ┆ April 9, 1998  ┆ Spike Feresten ┆ Andy     ┆ S09E17 │
│     ┆        ┆           ┆                 ┆                ┆                ┆ Ackerman ┆        │
│ 170 ┆ 9.0    ┆ 18        ┆ The Frogger     ┆ April 23, 1998 ┆ Gregg Kavet,   ┆ Andy     ┆ S09E18 │
│     ┆        ┆           ┆                 ┆                ┆ Andy Robin     ┆ Ackerman ┆        │
│ 171 ┆ 9.0    ┆ 19        ┆ The Maid        ┆ April 30, 1998 ┆ Alec Berg,     ┆ Andy     ┆ S09E19 │
│     ┆        ┆           ┆                 ┆                ┆ David Mandel,  ┆ Ackerman ┆        │
│     ┆        ┆           ┆                 ┆                ┆ Jeff …         ┆          ┆        │
│ 172 ┆ 9.0    ┆ 20        ┆ The Puerto      ┆ May 7, 1998    ┆ Alec Berg,     ┆ Andy     ┆ S09E20 │
│     ┆        ┆           ┆ Rican Day       ┆                ┆ Jennifer       ┆ Ackerman ┆        │
│     ┆        ┆           ┆                 ┆                ┆ Crittenden…    ┆          ┆        │
│ 173 ┆ 9.0    ┆ 23        ┆ The Finale      ┆ May 14, 1998   ┆ Larry David    ┆ Andy     ┆ S09E23 │
│     ┆        ┆           ┆                 ┆                ┆                ┆ Ackerman ┆        │
└─────┴────────┴───────────┴─────────────────┴────────────────┴────────────────┴──────────┴────────┘

In [67]:
df = episode_info.join(scripts, left_on="SEID", right_on="SEID", how="left").select(["EpisodeNo", "Title", "SEID", "Character", "Dialogue"])
df

shape: (55_173, 5)
┌───────────┬─────────────────────┬────────┬────────────┬─────────────────────────────────┐
│ EpisodeNo ┆ Title               ┆ SEID   ┆ Character  ┆ Dialogue                        │
│ ---       ┆ ---                 ┆ ---    ┆ ---        ┆ ---                             │
│ i8        ┆ str                 ┆ str    ┆ str        ┆ str                             │
╞═══════════╪═════════════════════╪════════╪════════════╪═════════════════════════════════╡
│ 1         ┆ Good News, Bad News ┆ S01E01 ┆ JERRY      ┆ Do you know what this is all a… │
│ 1         ┆ Good News, Bad News ┆ S01E01 ┆ JERRY      ┆ (pointing at Georges shirt) Se… │
│ 1         ┆ Good News, Bad News ┆ S01E01 ┆ GEORGE     ┆ Are you through?                │
│ 1         ┆ Good News, Bad News ┆ S01E01 ┆ JERRY      ┆ You do of course try on, when … │
│ 1         ┆ Good News, Bad News ┆ S01E01 ┆ GEORGE     ┆ Yes, it was purple, I liked it… │
│ …         ┆ …                   ┆ …      ┆ …          ┆ …                               │
│ 23        ┆ The Finale          ┆ S09E23 ┆ JERRY      ┆ Grand theft auto - don't steal… │
│ 23        ┆ The Finale          ┆ S09E23 ┆ PRISONER 3 ┆ You suck - I'm gonna cut you.   │
│ 23        ┆ The Finale          ┆ S09E23 ┆ JERRY      ┆ Hey, I don't come down to wher… │
│ 23        ┆ The Finale          ┆ S09E23 ┆ GUARD      ┆ Alright, Seinfeld, that's it. … │
│ 23        ┆ The Finale          ┆ S09E23 ┆ JERRY      ┆ Alright, hey, you've been grea… │
└───────────┴─────────────────────┴────────┴────────────┴─────────────────────────────────┘

In [36]:
episode_info = pl.read_csv(Path(datapath, "episode_info.csv"))

In [37]:
episode_info

shape: (174, 8)
┌─────┬────────┬───────────┬───────────────┬───────────────┬───────────────┬──────────────┬────────┐
│     ┆ Season ┆ EpisodeNo ┆ Title         ┆ AirDate       ┆ Writers       ┆ Director     ┆ SEID   │
│ --- ┆ ---    ┆ ---       ┆ ---           ┆ ---           ┆ ---           ┆ ---          ┆ ---    │
│ i64 ┆ f64    ┆ f64       ┆ str           ┆ str           ┆ str           ┆ str          ┆ str    │
╞═════╪════════╪═══════════╪═══════════════╪═══════════════╪═══════════════╪══════════════╪════════╡
│ 0   ┆ 1.0    ┆ 1.0       ┆ Good News,    ┆ July 5, 1989  ┆ Larry David,  ┆ Art Wolff    ┆ S01E01 │
│     ┆        ┆           ┆ Bad News      ┆               ┆ Jerry         ┆              ┆        │
│     ┆        ┆           ┆               ┆               ┆ Seinfeld      ┆              ┆        │
│ 1   ┆ 1.0    ┆ 1.0       ┆ The Stakeout  ┆ May 31, 1990  ┆ Larry David,  ┆ Tom Cherones ┆ S01E01 │
│     ┆        ┆           ┆               ┆               ┆ Jerry         ┆              ┆        │
│     ┆        ┆           ┆               ┆               ┆ Seinfeld      ┆              ┆        │
│ 2   ┆ 1.0    ┆ 2.0       ┆ The Robbery   ┆ June 7, 1990  ┆ Matt Goldman  ┆ Tom Cherones ┆ S01E02 │
│ 3   ┆ 1.0    ┆ 3.0       ┆ Male          ┆ June 14, 1990 ┆ Larry David,  ┆ Tom Cherones ┆ S01E03 │
│     ┆        ┆           ┆ Unbonding     ┆               ┆ Jerry         ┆              ┆        │
│     ┆        ┆           ┆               ┆               ┆ Seinfeld      ┆              ┆        │
│ 4   ┆ 1.0    ┆ 4.0       ┆ The Stock Tip ┆ June 21, 1990 ┆ Larry David,  ┆ Tom Cherones ┆ S01E04 │
│     ┆        ┆           ┆               ┆               ┆ Jerry         ┆              ┆        │
│     ┆        ┆           ┆               ┆               ┆ Seinfeld      ┆              ┆        │
│ …   ┆ …      ┆ …         ┆ …             ┆ …             ┆ …             ┆ …            ┆ …      │
│ 169 ┆ 9.0    ┆ 17.0      ┆ The Bookstore ┆ April 9, 1998 ┆ Spike         ┆ Andy         ┆ S09E17 │
│     ┆        ┆           ┆               ┆               ┆ Feresten      ┆ Ackerman     ┆        │
│ 170 ┆ 9.0    ┆ 18.0      ┆ The Frogger   ┆ April 23,     ┆ Gregg Kavet,  ┆ Andy         ┆ S09E18 │
│     ┆        ┆           ┆               ┆ 1998          ┆ Andy Robin    ┆ Ackerman     ┆        │
│ 171 ┆ 9.0    ┆ 19.0      ┆ The Maid      ┆ April 30,     ┆ Alec Berg,    ┆ Andy         ┆ S09E19 │
│     ┆        ┆           ┆               ┆ 1998          ┆ David Mandel, ┆ Ackerman     ┆        │
│     ┆        ┆           ┆               ┆               ┆ Jeff …        ┆              ┆        │
│ 172 ┆ 9.0    ┆ 20.0      ┆ The Puerto    ┆ May 7, 1998   ┆ Alec Berg,    ┆ Andy         ┆ S09E20 │
│     ┆        ┆           ┆ Rican Day     ┆               ┆ Jennifer      ┆ Ackerman     ┆        │
│     ┆        ┆           ┆               ┆               ┆ Crittenden…   ┆              ┆        │
│ 173 ┆ 9.0    ┆ 23.0      ┆ The Finale    ┆ May 14, 1998  ┆ Larry David   ┆ Andy         ┆ S09E23 │
│     ┆        ┆           ┆               ┆               ┆               ┆ Ackerman     ┆        │
└─────┴────────┴───────────┴───────────────┴───────────────┴───────────────┴──────────────┴────────┘